frase = "curso em video python"
print(frase.find('curso'))
print('curso' in frase)
print(frase[0::3])
print(frase.replace('curso','android'))
print(frase[0::3].upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase.strip())
print(frase.rstrip())
print(frase.lstrip())
print(frase.split())
print('-'.join(frase))
